### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by leearmee35**
Hello World Project @jasoncta

### CODE REVIEW

**Comment by jasoncta** [comment]
What are you doing Li?  @leearmee1988

**Comment by leearmee35** [comment]
web crawler project trying !

**Comment by leearmee35** [comment]
testing lol sorry for disturbing.

**Comment by jasoncta** [comment]
lol it's okay.  I want to finish a bunch of online courses before the next semester.

**Comment by leearmee35** [comment]
lol the funny thing is the online course which cost less than $100
sometimes far more better than our school lecture

**Comment by jasoncta** [comment]
haha, I know.  I actually prefer online courses.  The only problem is that recruiters don't value online education compared to attending an actual university.  
I'm trying to finish this specialization. 
https://www.coursera.org/specializations/java-object-oriented
After that I want to do the Algorithm specialization.

**Pull request merged**
